// apps/extension/entrypoints/admin/src/pages/dataSharePlan/TaskDataCountChart.tsx
import ReactEChartsCore from 'echarts-for-react/lib/core';
import { BarChart } from "echarts/charts";
import {
    DataZoomComponent,
    DataZoomSliderComponent,
    GridComponent,
    LegendComponent,
    TooltipComponent,
} from "echarts/components";
import * as echarts from 'echarts/core';
import { use } from "echarts/core";
import { CanvasRenderer } from "echarts/renderers";
import { StackBarData } from '../../data/chart/StackBarData';

use([
    CanvasRenderer,
    GridComponent,
    TooltipComponent,
    LegendComponent,
    DataZoomComponent,
    DataZoomSliderComponent,
    BarChart,
]);

interface TaskDataCountChartProps {
    data: StackBarData
}

const TaskDataCountChart: React.FC<TaskDataCountChartProps> = ({ data }) => {

    const option = {
        tooltip: {
            trigger: 'axis',
            axisPointer: {
                // Use axis to trigger tooltip
                type: 'shadow' // 'shadow' as default; can also be 'line' or 'shadow'
            }
        },
        legend: {},
        grid: {
            left: '3%',
            right: '4%',
            bottom: '3%',
            containLabel: true
        },
        dataZoom: [
            {
                id: 'dataZoomY',
                type: 'slider',
                yAxisIndex: [0],
                filterMode: 'empty'
            }
        ],
        xAxis: {
            type: 'value'
        },
        yAxis: {
            type: 'category',
            data: [...data.dateData]
        },
        series: data.seriesData.map(item => {
            return {
                name: item.name,
                type: 'bar',
                stack: 'total',
                label: {
                    show: true
                },
                color: item.color,
                emphasis: {
                    focus: 'series'
                },
                data: item.data
            }
        })
    };

    return <>
        <ReactEChartsCore
            echarts={echarts}
            option={option}
        />
    </>
}

export default TaskDataCountChart;

// src/sidepanel/views/components/TaskDataCountChart.vue
<template>
    <div>
        <div class="main">
            <div class="title">{{ props.title }}</div>
            <v-chart :loading="loading" autoresize :option="option" />
        </div>
    </div>
</template>
<script setup lang="ts">
import { BarChart } from "echarts/charts";
import {
    GridComponent,
    LegendComponent,
    TooltipComponent,
} from "echarts/components";
import { use } from "echarts/core";
import { CanvasRenderer } from "echarts/renderers";
import { onMounted, ref, watch } from "vue";
import VChart from "vue-echarts";

use([
    CanvasRenderer,
    GridComponent,
    TooltipComponent,
    LegendComponent,
    BarChart,
]);

const props = defineProps(["title"]);

const loading = ref(false);

const option = ref({
    tooltip: {
        trigger: 'axis',
        axisPointer: {
            // Use axis to trigger tooltip
            type: 'shadow' // 'shadow' as default; can also be 'line' or 'shadow'
        }
    },
    legend: {},
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis: {
        type: 'value'
    },
    yAxis: {
        type: 'category',
        data: []
    },
    series: [

    ]
});

const model = defineModel()

onMounted(() => {
});

watch(model, async (newValue, oldValue) => {
    if (JSON.stringify(newValue) !== JSON.stringify(oldValue)) {
        render();
    }
}
)

const render = async () => {
    loading.value = true;
    let modelValue = model.value;
    if (modelValue) {
        let seriesArray = [];
        modelValue.seriesData.forEach(item => {
            seriesArray.push({
                name: item.name,
                type: 'bar',
                stack: 'total',
                label: {
                    show: true
                },
                color:item.color,
                emphasis: {
                    focus: 'series'
                },
                data: item.data
            });
        });
        option.value.yAxis.data = modelValue.dateData;
        option.value.series = seriesArray;
        loading.value = false;
    }
}

</script>
<style lang="css" scoped>
.main {
    box-sizing: border-box;
    border: 1px solid #d0d7de;
    padding: 10px;
    border-radius: 5px;

    .title {
        font-size: 16px;
        font-weight: 600;
    }
}
</style>
